.\"  Copyright (C) 2019, Western Digital Corporation or its affiliates.
.\"  Written by Damien Le Moal <damien.lemoal@wdc.com>
.\"
.TH mkzonefs 8
.SH NAME
mkzonefs \- Create a zonefs file system on a zoned block device

.SH SYNOPSIS
.B mkzonefs
[
.B \-h|\-\-help
]
[
.B \-v
]
[
.B \-f
]
[
.B \-o
.I features
]
.I device

.SH DESCRIPTION
.B mkzonefs
is used to create a zonefs file system on a zoned block device.

.SH OPTIONS
.TP
.BI \-h
.BI \-\-help
Display a short usage message and return

.TP
.B \-v
Verbose output

.TP
.B \-f
Overwrite existing file system format on the device

.TP
.BI \-o " features"
.RS
Specify optional features. Features are comma separated and may take an
argument using the equal ("=") sign. The following extended features are
supported.
.TP
.BR aggr_cnv
Aggregate contiguous conventional zones into a single file.
Default: off (create one file per zone).
.TP
.BR uid =\fIUID\fR
Create files with \fIUID\fR as owner user. The default is "root" user (UID 0).
.TP
.BR gid =\fIGID\fR
Create files with \fIGID\fR as group owner. The default is "root" group (GID 0).
.TP
.BR perm =\fIpermissions\fR
Create files with \fIpermissions\fR as access rights. The default is "640".
.RE

.SH AUTHOR
This version of \fBmkzonefs\fR was written by Damien Le Moal.

.SH AVAILABILITY
.B mkzonefs
is available from https://github.com/westerndigitalcorporation/zonefs-tools/
